<?php
if (Mage::getStoreConfig('qixol/promo/enabled') == 0){
    return;
}
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php
$qixol_advertisment=Mage::getModel('qixol/advert');
$qixol_product_all_scripts_inside='';

/* BANNER - START */

    $qixol_product_top_box = Mage::getModel('qixol/bannerboxes')->load('PRODUCT_TOP');
    
    //if ($qixol_product_top_box->getBannerBoxIsActive()>0){
        $qixol_top_advertisment_text = $qixol_advertisment->getProductInfoTopAdv($_product);

        echo "<!-- PRODUCT BANNER: " . $qixol_top_advertisment_text . " -->";
        
        if ($qixol_top_advertisment_text!=''){
        $qixol_product_all_scripts_inside .= '$("#messages_product_view").after("<div id=product_top_ class=\'cycle-slideshow\' data-cycle-fx=\'';
        $qixol_product_all_scripts_inside .= $qixol_product_top_box->getBannerBoxTranslationType();
        $qixol_product_all_scripts_inside .= '\' data-cycle-timeout=\'1500\' data-cycle-slides=\'> div\'>';
        $qixol_product_all_scripts_inside .= preg_replace("/[\n\r]+/","",$qixol_top_advertisment_text);
        $qixol_product_all_scripts_inside .= '</div>"); $(\'#product_top_\').cycle();';
        }
    //}

    $qixol_product_inline_box=Mage::getModel('qixol/bannerboxes')->load('PRODUCT_INLINE');

    if ($qixol_product_inline_box->getBannerBoxIsActive()>0){
        $qixol_inline_advertisment_text=$qixol_advertisment->getProductInlineAdv($_product);

        if ($qixol_inline_advertisment_text!=''){
            $qixol_product_all_scripts_inside .= '$(".extra-info").after("<div=\'product_inline\' style=\'float: left;width: 100%;\' id=product_inline_ class=\'cycle-slideshow\' data-cycle-fx=\''.$qixol_product_inline_box->getBannerBoxTranslationType().'\' data-cycle-timeout=\'1500\' data-cycle-slides=\'> div\'>'.addslashes($qixol_inline_advertisment_text).'</div>");$(\'#product_inline_\').cycle();';
        }
    }

    /* BANNER - END */

    /* Promotion box on product page - START */
        
    if (Mage::getStoreConfig('qixol/stickers/showPromoBoxOnProductPage')>0){
    $qixol_all_promotions_text = $qixol_advertisment->getAllProductAdv($_product);
    if ($qixol_all_promotions_text!=''){
    //    $qixol_product_all_scripts_inside .= '$(".add-to-box").after("<div id=product_advertisment_ class=\'cycle-slideshow\' data-cycle-fx=\'scrollHorz\' data-cycle-timeout=\'1500\' data-cycle-slides=\'> div\'>'.preg_replace("/[\n\r]+/","",$qixol_all_promotions_text).'</div>"); $(\'#product_advertisment_\').cycle();';
         $qixol_product_all_scripts_inside .= '$(".add-to-cart").before("<div class=\'product_all_promotions\'><table style=\'width:100%\'><th>Offers</th>';
         $qixol_product_all_scripts_inside .= '<th style=\'width:100px;\'>You Save</th>';
         $qixol_product_all_scripts_inside .= preg_replace("/[\n\r]+/","",$qixol_all_promotions_text);
         $qixol_product_all_scripts_inside .= '</div></table>");';
    }
}

    /* Promotion box on product page - END */
        
    /* STICKERS - START */
    
    if (Mage::getStoreConfig('qixol/stickers/showStickersOnProductPage')>0) {

        $is_sticker_image = $qixol_advertisment->isSticked($_product);
    
    //    $is_sticker_image = [
    //        1 => 'http://localhost.magento.com/media/custom/stickers/File-1467816895.png',
    //        2 => 'http://localhost.magento.com/media/custom/stickers/bogof.png'];

    //    $is_sticker_image = 'http://localhost.magento.com/media/custom/stickers/File-1467816895.png';
    //    $is_sticker_image = 'http://localhost.magento.com/media/custom/stickers/bogof.png';

        // TODO: move this into css as a class
        $style = 'position: absolute; right: 65; top: 0; width: 100px; height: 100px; display: block; z-index: 2;';
        if ($is_sticker_image !== false){
        if (is_array($is_sticker_image)){
           $images_list='';
            foreach ($is_sticker_image as $image_add){
              $images_list.='<div style=\''.$style.' background:url(\"'.$image_add.'\") 0 0 no-repeat;background-size:contain;\'></div>';
            }
            if ($images_list!='')
                $qixol_product_all_scripts_inside.='$(".product-image-gallery").after("<div id=stickers_ ';
                $qixol_product_all_scripts_inside.=' style=\''.$style.'\'';
                $qixol_product_all_scripts_inside.=' class=\'cycle-slideshow\' ';
                //$qixol_product_all_scripts_inside.='data-cycle-fx=\''.$qixol_bannerbox_product_stickers->getBannerBoxTranslationType().'\' ";';
                $qixol_product_all_scripts_inside.='data-cycle-fx=\''.'fadeout'.'\' ';
                $qixol_product_all_scripts_inside.='data-cycle-timeout=\'555\' data-cycle-slides=\'> div\'>';
                $qixol_product_all_scripts_inside.=$images_list;
                $qixol_product_all_scripts_inside.='</div>");$(\'#stickers_\').cycle();';

        } else {
          $qixol_product_all_scripts_inside.='$(".product-image-gallery").after("<div style=\''.$style.' background:url(\"'.$is_sticker_image.'\") 0 0 no-repeat;\'></div>");';
        }

        }
    }  

    /* STICKERS - END */
    
    if ($qixol_product_all_scripts_inside!=''){
        ?><script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>lib/jquery/jquery-1.10.2.min.js"></script><script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>/skin/frontend/base/default/js/lib/jquery.cycle2.min.js"></script><script type="text/javascript">$.noConflict();jQuery( document ).ready(function( $ ) { <?php echo $qixol_product_all_scripts_inside;?>});</script><?php
    }
