<?php ?>
<div class="block block-progress opc-block-progress">
    <!-- THIS IS A TEST FROM BASE PROGRESS TEMPLATE -->
    <div class="block-title">
        <strong><span><?php echo $this->__('Your Checkout Progress') ?></span></strong>
    </div>
    <div class="block-content">
        <dl>
            <?php if ($this->getCheckout()->getStepData('missedpromotions', 'is_show')): ?>
            <?php if($this->getCheckout()->getStepData('missedpromotions', 'complete')): ?>
                <dt class="complete">
                    <?php echo $this->__('Missed Promotions') ?> <span class="separator">|</span> <a href="#missedpromotions" onclick="checkout.accordion.openSection('opc-missedpromotions'); return false;"><?php echo $this->__('Change') ?></a>
                </dt>
                <dd class="complete">
                    <div>
                        <?php echo $this->__('Missed Promotions XXXXXX Is: ');?>
                        <?php
                            $like = $this->getQuote()->getMissedpromotionsLike();
                            if($like == 1){
                                echo $this->__('Yes');
                            } else{
                                echo $this->__('No');
                            }
                        ?>
                    </div>
                </dd>
            <?php else: ?>
                <dt>
                    <?php echo $this->__('Missed Promotions - is_show not set') ?>
                </dt>
            <?php endif; ?>
            <?php endif; ?>
            <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
            <div id="billing-progress-opcheckout">
                <?php echo $this->getChildHtml('billing.progress') ?>
            </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
            <div id="shipping-progress-opcheckout">
                <?php echo $this->getChildHtml('shipping.progress') ?>
            </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
            <div id="shipping_method-progress-opcheckout">
                <?php echo $this->getChildHtml('shippingmethod.progress') ?>
            </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
            <div id="payment-progress-opcheckout">
                <?php echo $this->getChildHtml('payment.progress') ?>
            </div>
            <?php endif; ?>
        </dl>
    </div>
</div>

