<?php
/*
moved to mincart
         //$place_box_in_design_after_pattern=Mage::getStoreConfig('qixol/integraion/boxcartpromotion')
         $place_box_in_design_after_pattern='.cart';

/*
         $inline_cart_advert='';

         //for cart items
          $cart = Mage::getModel('checkout/cart')->getQuote();
          foreach ($cart->getAllItems() as $item) {
              if (isset($_SESSION['qixol_quoted_items'])&&isset($_SESSION['qixol_quoted_items']['items'][$item->getId()])){
                  if (isset($_SESSION['qixol_quoted_items']['items'][$item->getId()]['promotions']))
                     foreach ($_SESSION['qixol_quoted_items']['items'][$item->getId()]['promotions'] as $promotion){
//inline level promotion
if ((int)$promotion['basketlevel']==0&&isset($_SESSION['qixol_quoted_items']['summary'][$promotion['id']]))
                       $inline_cart_advert.="
$('<div class=\"cart_inline_item_promo\">".addslashes($_SESSION['qixol_quoted_items']['summary'][$promotion['id']]['data']['display_text'])."</div>').appendTo($('#qixol_idx_mcart_item_name_".$item->getId()."'));
";
//basket level promotion
if ((int)$promotion['basketlevel']==1&&isset($_SESSION['qixol_quoted_items']['summary'][$promotion['id']]))
        $text_to_show_cart_adv.='';//should be also added??? $_SESSION['qixol_quoted_items']['summary'][$promotion['id']]['display_text'];

                     }

//if quantity changed (get one + one free so will be splited to 2 products with 1 free)
if ($_SESSION['qixol_quoted_items']['items'][$item->getId()]['updated_qty']>0)
$inline_cart_advert.="
$('<div class=\"cart_inline_item_new_qty\">For&nbsp;promo&nbsp;".addslashes($_SESSION['qixol_quoted_items']['items'][$item->getId()]['data']['quantity'])."&nbsp;Qty</div>').appendTo($('#qixol_idx_mcart_item_qty_".$item->getId()."'));
"; 

if ($_SESSION['qixol_quoted_items']['items'][$item->getId()]['updated_price']>0)
$inline_cart_advert.="
$('<div class=\"cart_inline_item_new_price\">Only for ".addslashes($this->helper('checkout')->formatPrice($_SESSION['qixol_quoted_items']['items'][$item->getId()]['data']['lineamount']))."</div>').appendTo($('#qixol_idx_mcart_item_price_".$item->getId()."'));
"; 

              }
          }
$total_discount_amount=0;
if (isset($_SESSION['qixol_quoted_items']['items'])){
   foreach ($_SESSION['qixol_quoted_items']['items'] as $cart_item_process){
      if ($cart_item_process['data']['totaldiscount']>0&&(int)$cart_item_process['new']==0){
            $total_discount_amount+=$cart_item_process['data']['totaldiscount'];
     }
  }
}

if ($text_to_show_cart_adv!==false&&strlen($text_to_show_cart_adv)>5||$inline_cart_advert!=''){         
?><script type="text/javascript" src="/js/lib/jquery/jquery-1.10.2.min.js"></script><script type="text/javascript">$.noConflict();jQuery( document ).ready(function( $ ) { <?php 
/*if ($text_to_show_cart_adv!==false&&strlen($text_to_show_cart_adv)>5)
echo '$("'.$place_box_in_design_after_pattern.'").after("<div class=\'qixolcartpromo\'>'.$text_to_show_cart_adv.'</div>");';*//*
if ($inline_cart_advert!='')
echo preg_replace("/[\n\r]+/","",$inline_cart_advert);
if ($total_discount_amount>0){
/*?>$('<tr class="qixol_discount"><td class="a-right" colspan="1" > Discount</td><td class="a-right" ><span class="qixol_total_price"><?php echo $this->helper('checkout')->formatPrice($total_discount_amount);; ?></span></td></tr>').appendTo($('#shopping-cart-totals-table tbody'));<?php*//*
?>$('#header-cart .subtotal .price').addClass('qixol_price_cross');$('<?php echo $this->helper('checkout')->formatPrice($cart->getGrandTotal()-$total_discount_amount); ?>').appendTo($('#header-cart .subtotal .price').parent());<?php
}
?>});</script><?php
}*/
?>
