<?php ?>
<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Banner images') ?></h4>

<!--<script type="text/javascript">
            
    function addImage() {
        window.location.href = '<?php $this->getUrl('*/*/saverole') ?>';
    }

</script>

<button id="id_<?php $this->getHtmlId() ?>" title="Add image" type="button" class="scalable save" onclick="addImage()" style=""><span><span><span>Add image</span></span></span></button>-->

    <?php echo $this->_getGridHtml() ?>
