<form id="co-missedpromotions-form" action="">
<fieldset>
    <ul class="form-list">
    <li id="missedpromotions-form">
        <fieldset>
            <ul>
                <li class="wide">
                    <label for="missedpromotions:like" class="required"><em>*</em><?php echo $this->__('Do you like Missedpromotions Magento Blog?') ?></label>
                    <div class="input-box">
                        <select class="required-entry" name="missedpromotions[like]" id="missedpromotions:like">
                            <option value=''><?php echo $this->__('Please Choose..');?></option>
                            <option value='1' <?php if($this->getQuote()->getMissedpromotionsLike() == 1){echo 'selected="selected"';} ?>><?php echo $this->__('Yes');?></option>
                            <option value='2' <?php if($this->getQuote()->getMissedpromotionsLike() == 2){echo 'selected="selected"';} ?>><?php echo $this->__('No');?></option>
                        </select>
                    </div>
                </li>
            </ul>
        </fieldset>
     </li>
    </ul>
    <div class="buttons-set" id="missedpromotions-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="missedpromotions.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="missedpromotions-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var missedpromotions = new MissedPromotions('co-missedpromotions-form','<?php echo $this->getUrl('qixolmissedpromotions/checkout/onepage/saveMissedpromotions') ?>');
    var missedpromotionsForm = new VarienForm('co-missedpromotions-form');
//]]>
</script>